version: '3'
services:
  app:
    build: .
    container_name: Ahentai
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - /mydata/Ahentai/src:/src
    ports:
      - "8000:8000"
    restart: always
  db:
    image: mysql:5.7
    volumes:
      - /mydata/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=0d000721
      - MYSQL_DATABASE=Doujinshi_management_system
#  nginx:
#    restart: always
#    image: nginx:latest
#    ports:
#      - "8000:8000"
#    volumes:
#      - /mydata/nginx/static-volume:/code/collected_static
#      - /mydata/nginx/config/nginx:/etc/nginx/conf.d
#    depends_on:
#      - app
#    networks:
#      - web_network
#networks:
#  web_network:
#    driver: bridge
#  db_network:
#    driver: bridge
#
#volumes:
#  static-volume: