version: "3"
services:
  app:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/akaimoe/ahentai:1.0.1
#    container_name: Ahentai
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - /mydata/Ahentai/media/content:/src/Ahentai/media/content
      - /mydata/Ahentai/media/cover:/src/Ahentai/media/cover
      - /mydata/Ahentai/media/source:/src/Ahentai/media/source
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    volumes:
      - /mydata/mysql_djg:/var/lib/mysql
    ports:
      - "3306:3306"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
#      --explicit_defaults_for_timestamp=true
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=0d000721
      - MYSQL_DATABASE=Doujinshi_management_system
#  nginx:
#    restart: always
#    image: nginx:latest
#    ports:
#      - "8000:8000"
#    volumes:
#      - /mydata/nginx/static-volume:/code/collected_static
#      - /mydata/nginx/config/nginx:/etc/nginx/conf.d
#    depends_on:
#      - app
#    networks:
#      - web_network
#networks:
#  web_network:
#    driver: bridge
#  db_network:
#    driver: bridge
#
#volumes:
#  static-volume: