# Generated by Django 4.2.6 on 2023-11-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('tag', models.CharField(blank=True, max_length=80)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('author', models.CharField(blank=True, max_length=40)),
                ('introduction', models.CharField(blank=True, max_length=999)),
                ('upload_user', models.BigIntegerField()),
                ('upload_date', models.DateField()),
                ('reading_volume', models.IntegerField(blank=True, default=0)),
                ('like_volume', models.IntegerField(blank=True, default=0)),
                ('collect_volume', models.IntegerField(default=0)),
                ('cover', models.ImageField(upload_to='cover/')),
                ('content', models.CharField(blank=True, max_length=100)),
                ('like_list', models.CharField(blank=True, max_length=9999)),
            ],
        ),
    ]
