# Generated by Django 4.2.6 on 2023-11-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='like_list',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
