# Generated by Django 4.2.6 on 2023-11-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_alter_comic_like_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='like_list',
        ),
    ]
