# Generated by Django 4.2.6 on 2023-11-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0004_user_collect_user_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('comic_id', models.BigIntegerField()),
            ],
        ),
    ]
