# Generated by Django 4.2.6 on 2023-11-03 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comic', '0005_user_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_collect',
            name='comic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.comic'),
        ),
        migrations.AlterField(
            model_name='user_collect',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
