# Generated by Django 4.2.6 on 2023-11-03 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0006_alter_user_collect_comic_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_collect',
            old_name='comic_id',
            new_name='comic',
        ),
        migrations.RenameField(
            model_name='user_collect',
            old_name='user_id',
            new_name='user',
        ),
    ]
