# Generated by Django 4.2.6 on 2023-11-03 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='collect',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='like',
        ),
    ]
