# Generated by Django 4.2.6 on 2023-11-03 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userinfo_collect_remove_userinfo_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='history',
        ),
    ]
